version: '3.7'

services:
  siruntu_app:
    build:
      args:
        user: siruntu
        uid: 1000
      context: ./
      dockerfile: siruntu-app.dockerfile
    image: irhamsahbana/siruntu-app:latest
    container_name: siruntu-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - siruntu
    depends_on:
      - siruntu_db
    links:
      - siruntu_db
    extra_hosts:
      - "host.docker.internal:host-gateway"

  siruntu_nginx:
    image: nginx:1.21.6-alpine
    container_name: siruntu-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./etc/nginx:/etc/nginx/conf.d
    networks:
      - siruntu

  siruntu_db:
    container_name: siruntu-db
    image: mariadb:10.3
    restart: always
    networks:
      - siruntu
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
      - ./etc/my.cnf.d:/etc/mysql/conf.d
    env_file:
     - .env.docker

  siruntu_kurento:
    image: kurento/kurento-media-server:6.16.0
    container_name: siruntu-kurento
    restart: unless-stopped
    ports:
      - 8888:8888
    volumes:
      - ./:/var/www
      - ./temp:/tmp
    network_mode: "host"
    env_file:
      - .env.docker

  siruntu_coturn:
    image: instrumentisto/coturn:4
    container_name: siruntu-coturn
    volumes:
      - ./etc/coturn.d/coturn.conf:/etc/coturn/turnserver.conf
    network_mode: "host"

networks:
  siruntu: {}
